# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.5.6
maven_group=de.tomalbrc
archives_base_name=danse

# Dependencies
fabric_version=0.152.1+26.2
# https://github.com/Patbox/polymer/releases
polymer_version=0.17.0+26.2-rc-2
# https://github.com/Patbox/map-canvas-api/releases
mapcanvas_version=0.9.0+26.2
dialogutils_version=1.8.4+26.1
papi_version=3.1.0-beta.1+26.2
sgui_version=2.1.0+26.2
